### ISSUE TITLE
Feature Request: Suppress selfie prompt on subsequent image uploads within a round

### ISSUE THREAD

**Issue by StensigITMinds** [IT-Minds/coffee_bot#57]
In the current state the bot will continue to prompt you when you upload an image in the chat, asking whether it's a selfie, even after you've submitted a selfie and confirmed it. 

It would be nice to have the bot supresss these prompts if it can see that the user has already submitted and confirmed a selfie, and preferably also if another user posts images while having been accepted in a user's selfie submission. For obvious reasons this supresseion should only last without the context of one round, and would reset each round until a new selfie submission has been confirmed.

**Comment by objmj-itminds** [comment]
The naive solution could be as follows...

```git
--- a/backend/Application/ImagePost/Commands/ImagePostCommand/ImagePostCommand.cs
+++ b/backend/Application/ImagePost/Commands/ImagePostCommand/ImagePostCommand.cs
@@ -38,6 +38,8 @@ namespace Application.ImagePost.Commands.ImagePostCommand
           .Where(x => x.CoffeeRound.SlackChannelId == request.Event.ChannelId && x.CoffeeRound.Active)
           .FirstOrDefaultAsync();

+        if (group.HasPhoto) return 1;
+
         var file = await slackClient.Client().Files.Info(fileId: request.FileId);
         if (group != null) {
           group.SlackPhotoUrl = file.File.UrlPrivate;
```

It limits possible human errors. If an image wasn't a group selfie, but the post creator initially said "yes" to the prompt, a new image can no longer be added.
