### ISSUE TITLE
Feature Request: Set automatic unpause date, when pausing membership

### ISSUE THREAD

**Issue by phillip-itminds** [IT-Minds/coffee_bot#59]
**Is your feature request related to a problem? Please describe.**
When going on vacation, I have to pause the membership, but I have to also remember to unpause the membership when I get back. It would be nice to be able to set a date for an automatic unpause when pausing membership.

**Describe the solution you'd like**
When pausing membership, the app could ask if it should automatically unpause it at a specified date. If a date is selected, then membership will be unpaused when the date is reached. This could be a model opening up when pausing or a button to set/edit the date besides the pause button.

**Describe alternatives you've considered**
No alternatives have been considered.

**Additional context**
N/A

**Comment by objmj-itminds** [comment]
Closed in 733d5d5795fff03072e6408327395de413f0bf36
